# Generated by Django 3.1.5 on 2021-02-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_usuarionivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='UsuarioNivel',
            field=models.CharField(default='BASICO', max_length=20),
        ),
    ]
